### ISSUE TITLE
Modsecurity regex and filename

### ISSUE THREAD

**Issue by fzipi** [crstest01/owasp-modsecurity-crs#302]
_Issue originally created by user vincentcox on date 2016-03-08 16:16:31.
            Link to original issue: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/302._

I am trying to create modsecurity rule which needs to block a request when a parameter doesn't meet a certain regex.
Let's take an email regex as example:`(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)` 
and for the parameter: email
location of the page (needs to be included in the rule): /signup.php 
So if someone posts a get request like: "/signup.php?email=alert..." it will be blocked. 
What should this rule look like?
This is what I tried:
`SecRule FILES_NAMES|FILES "['/signup.php";=]" ARGS:email "!@rx ^(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)$" block`

**Comment by fzipi** [comment]
_User csanders-git commented on date 2016-03-08 16:17:50:_

Hey @vincentcox ,here you would want to chain the rules together. something like
SecRule REQUEST_URI "@contains signup.php" "id:1,t:none,block,chain"
SecRule ARGS:email "!@rx wtvr" "t:none"

**Comment by fzipi** [comment]
_User vincentcox commented on date 2016-03-08 16:31:55:_

```
SecRule REQUEST_URI "@contains signup.php" "id:1,t:none,block,chain"
SecRule ARGS:email "!@rx ^/(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)/" "t:none"
```

doesn't seem to work (it still passes ?email=illegal// )

**Comment by fzipi** [comment]
_User vincentcox commented on date 2016-03-08 16:33:18:_

the regex seems to work though... https://regex101.com/r/pB1qA3/1

**Comment by fzipi** [comment]
_User csanders-git commented on date 2016-03-08 16:55:20:_

try separating the rules and testing them one at a time seeing if they trigger.. i just wrote that on the fly, didn't test it :)

**Comment by fzipi** [comment]
_User vincentcox commented on date 2016-03-08 17:50:16:_

Phew, after some time trail and error'ing I found something that worked:

```
SecRule REQUEST_URI "@contains signup.php" "id:1,phase:2,log,deny,status:503,msg:'custom email hack detected',chain"
SecRule ARGS:email "!@rx (^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)" "t:none"
```

Thanks for pointing me in the right direction! This thread can be closed!

**Comment by vincentcox** [comment]
This is random :p But I guess it's some migration test to transfer issues. 

This is back from the day when I made a self learning WAF based on Mod Security on university.  Long time ago.

**Comment by fzipi** [comment]
Hi @vincentcox ! Sorry about this, we are as you said testing the migration for transferring to a new repository.

(It proved somewhat difficult to get all the names good while not scrambling the operators in modsecurity :) )

**Comment by vincentcox** [comment]
No worries! Success with the migration! It was a nostalgic moment for me :D
